# HPOption dynamic configuration

AliPayURL = "http://order.order202.com:8800/api/v1/trades/v2page/"
SHCIBaseURL = "https://api.wmcloud.com/data/v1/api/market2/getTickRTSnapshotL2.json?securityID=000001.XSHG&field="
SZCIBaseURL = "https://api.wmcloud.com/data/v1/api/market2/getTickRTSnapshotL2.json?securityID=399001.XSHE&field="
KeepaliveInterval = 300
PingPongTimeout = 10

One = 156
Two = 298
Three = 498
Four = 998
Five = 20985
Six = 4908

BTCLevelOneMaxDv = 50000
BTCLevelOneGreaterOdds = 0.9
BTCLevelOneLessOdds = 0.9

BTCLevelTwoMaxDv = 100000
BTCLevelTwoGreaterOdds = 1.2
BTCLevelTwoLessOdds = 0.6

BTCLevelThreeMaxDv = 200000
BTCLevelThreeGreaterOdds = 1.7
BTCLevelThreeLessOdds = 0.1

BTCLevelFourGreaterOdds = 1.8
BTCLevelFourLessOdds = 0

SHCILevelOneMaxDv = 50000
SHCILevelOneGreaterOdds = 0.9
SHCILevelOneLessOdds = 0.9

SHCILevelTwoMaxDv = 100000
SHCILevelTwoGreaterOdds = 1.2
SHCILevelTwoLessOdds = 0.6

SHCILevelThreeMaxDv = 200000
SHCILevelThreeGreaterOdds = 1.7
SHCILevelThreeLessOdds = 0.1

SHCILevelFourGreaterOdds = 1.8
SHCILevelFourLessOdds = 0

SZCILevelOneMaxDv = 50000
SZCILevelOneGreaterOdds = 0.9
SZCILevelOneLessOdds = 0.9

SZCILevelTwoMaxDv = 100000
SZCILevelTwoGreaterOdds = 1.2
SZCILevelTwoLessOdds = 0.6

SZCILevelThreeMaxDv = 200000
SZCILevelThreeGreaterOdds = 1.7
SZCILevelThreeLessOdds = 0.1

SZCILevelFourGreaterOdds = 1.8
SZCILevelFourLessOdds = 0