// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hp.proto

package hpgrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuotationReqData struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotationReqData) Reset()         { *m = QuotationReqData{} }
func (m *QuotationReqData) String() string { return proto.CompactTextString(m) }
func (*QuotationReqData) ProtoMessage()    {}
func (*QuotationReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{0}
}

func (m *QuotationReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotationReqData.Unmarshal(m, b)
}
func (m *QuotationReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotationReqData.Marshal(b, m, deterministic)
}
func (m *QuotationReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotationReqData.Merge(m, src)
}
func (m *QuotationReqData) XXX_Size() int {
	return xxx_messageInfo_QuotationReqData.Size(m)
}
func (m *QuotationReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotationReqData.DiscardUnknown(m)
}

var xxx_messageInfo_QuotationReqData proto.InternalMessageInfo

func (m *QuotationReqData) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *QuotationReqData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SettleResData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid                  string   `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Handletime           int64    `protobuf:"varint,3,opt,name=handletime,proto3" json:"handletime,omitempty"`
	Settletime           int64    `protobuf:"varint,4,opt,name=settletime,proto3" json:"settletime,omitempty"`
	Inputamount          float64  `protobuf:"fixed64,5,opt,name=inputamount,proto3" json:"inputamount,omitempty"`
	Outputamount         float64  `protobuf:"fixed64,6,opt,name=outputamount,proto3" json:"outputamount,omitempty"`
	Ordervalue           float64  `protobuf:"fixed64,7,opt,name=ordervalue,proto3" json:"ordervalue,omitempty"`
	Settlevalue          float64  `protobuf:"fixed64,8,opt,name=settlevalue,proto3" json:"settlevalue,omitempty"`
	Side                 uint32   `protobuf:"varint,9,opt,name=side,proto3" json:"side,omitempty"`
	Interval             uint32   `protobuf:"varint,10,opt,name=interval,proto3" json:"interval,omitempty"`
	Symbol               string   `protobuf:"bytes,11,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Orderresult          int32    `protobuf:"varint,12,opt,name=orderresult,proto3" json:"orderresult,omitempty"`
	Balance              float64  `protobuf:"fixed64,13,opt,name=binance,proto3" json:"binance,omitempty"`
	Vitualbalance        float64  `protobuf:"fixed64,14,opt,name=vitualbalance,proto3" json:"vitualbalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleResData) Reset()         { *m = SettleResData{} }
func (m *SettleResData) String() string { return proto.CompactTextString(m) }
func (*SettleResData) ProtoMessage()    {}
func (*SettleResData) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{1}
}

func (m *SettleResData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleResData.Unmarshal(m, b)
}
func (m *SettleResData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleResData.Marshal(b, m, deterministic)
}
func (m *SettleResData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleResData.Merge(m, src)
}
func (m *SettleResData) XXX_Size() int {
	return xxx_messageInfo_SettleResData.Size(m)
}
func (m *SettleResData) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleResData.DiscardUnknown(m)
}

var xxx_messageInfo_SettleResData proto.InternalMessageInfo

func (m *SettleResData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SettleResData) GetTid() string {
	if m != nil {
		return m.Tid
	}
	return ""
}

func (m *SettleResData) GetHandletime() int64 {
	if m != nil {
		return m.Handletime
	}
	return 0
}

func (m *SettleResData) GetSettletime() int64 {
	if m != nil {
		return m.Settletime
	}
	return 0
}

func (m *SettleResData) GetInputamount() float64 {
	if m != nil {
		return m.Inputamount
	}
	return 0
}

func (m *SettleResData) GetOutputamount() float64 {
	if m != nil {
		return m.Outputamount
	}
	return 0
}

func (m *SettleResData) GetOrdervalue() float64 {
	if m != nil {
		return m.Ordervalue
	}
	return 0
}

func (m *SettleResData) GetSettlevalue() float64 {
	if m != nil {
		return m.Settlevalue
	}
	return 0
}

func (m *SettleResData) GetSide() uint32 {
	if m != nil {
		return m.Side
	}
	return 0
}

func (m *SettleResData) GetInterval() uint32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *SettleResData) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SettleResData) GetOrderresult() int32 {
	if m != nil {
		return m.Orderresult
	}
	return 0
}

func (m *SettleResData) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *SettleResData) GetVitualbalance() float64 {
	if m != nil {
		return m.Vitualbalance
	}
	return 0
}

func init() {
	proto.RegisterType((*QuotationReqData)(nil), "QuotationReqData")
	proto.RegisterType((*SettleResData)(nil), "SettleResData")
}

func init() { proto.RegisterFile("hp.proto", fileDescriptor_69f0e71e027708c3) }

var fileDescriptor_69f0e71e027708c3 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xc1, 0x4b, 0xeb, 0x40,
	0x10, 0xc6, 0xdf, 0xbe, 0xb4, 0x69, 0x32, 0x6d, 0x4a, 0xdf, 0x3e, 0x91, 0xa5, 0x88, 0x84, 0xe0,
	0x21, 0xa7, 0x22, 0x7a, 0xf7, 0x20, 0x22, 0xde, 0xc4, 0xf5, 0xe6, 0x6d, 0xdb, 0x2c, 0x76, 0x21,
	0xc9, 0xc6, 0x64, 0xb6, 0xe0, 0x1f, 0xe4, 0xff, 0x29, 0x3b, 0xb1, 0x6d, 0xea, 0x6d, 0xe6, 0xf7,
	0x4d, 0xbe, 0x6f, 0xc9, 0x0c, 0x44, 0xdb, 0x66, 0xd5, 0xb4, 0x16, 0x6d, 0xf6, 0x08, 0x8b, 0x17,
	0x67, 0x51, 0xa1, 0xb1, 0xb5, 0xd4, 0x1f, 0x0f, 0x0a, 0x15, 0x3f, 0x83, 0x71, 0xd3, 0x9a, 0x8d,
	0x16, 0x2c, 0x65, 0x39, 0x93, 0x7d, 0xc3, 0x2f, 0x20, 0x46, 0x53, 0xe9, 0x0e, 0x55, 0xd5, 0x88,
	0xbf, 0x29, 0xcb, 0x03, 0x79, 0x04, 0xd9, 0x57, 0x00, 0xc9, 0xab, 0x46, 0x2c, 0xb5, 0xd4, 0x1d,
	0xb9, 0x2c, 0x20, 0x70, 0xa6, 0x20, 0x8f, 0x58, 0xfa, 0xd2, 0x13, 0x34, 0x05, 0x7d, 0x1b, 0x4b,
	0x5f, 0xf2, 0x4b, 0x80, 0xad, 0xaa, 0x8b, 0x52, 0x7b, 0x23, 0x11, 0x90, 0xe9, 0x80, 0x78, 0xbd,
	0x23, 0x53, 0xd2, 0x47, 0xbd, 0x7e, 0x24, 0x3c, 0x85, 0xa9, 0xa9, 0x1b, 0x87, 0xaa, 0xb2, 0xae,
	0x46, 0x31, 0xa6, 0xf7, 0x0e, 0x11, 0xcf, 0x60, 0x66, 0x1d, 0x1e, 0x47, 0x42, 0x1a, 0x39, 0x61,
	0x3e, 0xc5, 0xb6, 0x85, 0x6e, 0x77, 0xaa, 0x74, 0x5a, 0x4c, 0x68, 0x62, 0x40, 0x7c, 0x4a, 0x9f,
	0xd9, 0x0f, 0x44, 0x7d, 0xca, 0x00, 0x71, 0x0e, 0xa3, 0xce, 0x14, 0x5a, 0xc4, 0x29, 0xcb, 0x13,
	0x49, 0x35, 0x5f, 0x42, 0x64, 0x6a, 0x24, 0x0f, 0x01, 0xc4, 0x0f, 0x3d, 0x3f, 0x87, 0xb0, 0xfb,
	0xac, 0xd6, 0xb6, 0x14, 0x53, 0xfa, 0x19, 0x3f, 0x9d, 0x4f, 0xa2, 0xdc, 0x56, 0x77, 0xae, 0x44,
	0x31, 0x4b, 0x59, 0x3e, 0x96, 0x43, 0xc4, 0x05, 0x4c, 0xd6, 0xaa, 0x54, 0xf5, 0x46, 0x8b, 0x84,
	0xde, 0xb1, 0x6f, 0xf9, 0x15, 0x24, 0x3b, 0x83, 0x4e, 0x95, 0x7b, 0x7d, 0x4e, 0xfa, 0x29, 0xbc,
	0x79, 0x86, 0xe4, 0xa9, 0x79, 0x6f, 0x9b, 0x4d, 0xa7, 0xdb, 0x9d, 0x5f, 0xeb, 0x1d, 0xfc, 0x3f,
	0x1c, 0x40, 0xbf, 0x40, 0xda, 0xde, 0xbf, 0xd5, 0xef, 0xb3, 0x58, 0xce, 0x57, 0x27, 0x0b, 0xce,
	0xfe, 0xe4, 0xec, 0x9a, 0xdd, 0x47, 0x6f, 0xe1, 0x96, 0x0c, 0xd7, 0x21, 0x5d, 0xd4, 0xed, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x45, 0xdd, 0xb1, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HpgrpcserviceClient is the client API for Hpgrpcservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HpgrpcserviceClient interface {
	QuotationSettleData(ctx context.Context, opts ...grpc.CallOption) (Hpgrpcservice_QuotationSettleDataClient, error)
}

type hpgrpcserviceClient struct {
	cc *grpc.ClientConn
}

func NewHpgrpcserviceClient(cc *grpc.ClientConn) HpgrpcserviceClient {
	return &hpgrpcserviceClient{cc}
}

func (c *hpgrpcserviceClient) QuotationSettleData(ctx context.Context, opts ...grpc.CallOption) (Hpgrpcservice_QuotationSettleDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Hpgrpcservice_serviceDesc.Streams[0], "/Hpgrpcservice/QuotationSettleData", opts...)
	if err != nil {
		return nil, err
	}
	x := &hpgrpcserviceQuotationSettleDataClient{stream}
	return x, nil
}

type Hpgrpcservice_QuotationSettleDataClient interface {
	Send(*QuotationReqData) error
	Recv() (*SettleResData, error)
	grpc.ClientStream
}

type hpgrpcserviceQuotationSettleDataClient struct {
	grpc.ClientStream
}

func (x *hpgrpcserviceQuotationSettleDataClient) Send(m *QuotationReqData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hpgrpcserviceQuotationSettleDataClient) Recv() (*SettleResData, error) {
	m := new(SettleResData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HpgrpcserviceServer is the server API for Hpgrpcservice service.
type HpgrpcserviceServer interface {
	QuotationSettleData(Hpgrpcservice_QuotationSettleDataServer) error
}

// UnimplementedHpgrpcserviceServer can be embedded to have forward compatible implementations.
type UnimplementedHpgrpcserviceServer struct {
}

func (*UnimplementedHpgrpcserviceServer) QuotationSettleData(srv Hpgrpcservice_QuotationSettleDataServer) error {
	return status.Errorf(codes.Unimplemented, "method QuotationSettleData not implemented")
}

func RegisterHpgrpcserviceServer(s *grpc.Server, srv HpgrpcserviceServer) {
	s.RegisterService(&_Hpgrpcservice_serviceDesc, srv)
}

func _Hpgrpcservice_QuotationSettleData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HpgrpcserviceServer).QuotationSettleData(&hpgrpcserviceQuotationSettleDataServer{stream})
}

type Hpgrpcservice_QuotationSettleDataServer interface {
	Send(*SettleResData) error
	Recv() (*QuotationReqData, error)
	grpc.ServerStream
}

type hpgrpcserviceQuotationSettleDataServer struct {
	grpc.ServerStream
}

func (x *hpgrpcserviceQuotationSettleDataServer) Send(m *SettleResData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hpgrpcserviceQuotationSettleDataServer) Recv() (*QuotationReqData, error) {
	m := new(QuotationReqData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Hpgrpcservice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Hpgrpcservice",
	HandlerType: (*HpgrpcserviceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QuotationSettleData",
			Handler:       _Hpgrpcservice_QuotationSettleData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hp.proto",
}
